// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: sensor/v1/sensor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Messages cho MonitorTemperature ---
type MonitorTemperatureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensorId string `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
}

func (x *MonitorTemperatureRequest) Reset() {
	*x = MonitorTemperatureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensor_v1_sensor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonitorTemperatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorTemperatureRequest) ProtoMessage() {}

func (x *MonitorTemperatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_v1_sensor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorTemperatureRequest.ProtoReflect.Descriptor instead.
func (*MonitorTemperatureRequest) Descriptor() ([]byte, []int) {
	return file_sensor_v1_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *MonitorTemperatureRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

type MonitorTemperatureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temperature float32 `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Timestamp   string  `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *MonitorTemperatureResponse) Reset() {
	*x = MonitorTemperatureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensor_v1_sensor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonitorTemperatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorTemperatureResponse) ProtoMessage() {}

func (x *MonitorTemperatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_v1_sensor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorTemperatureResponse.ProtoReflect.Descriptor instead.
func (*MonitorTemperatureResponse) Descriptor() ([]byte, []int) {
	return file_sensor_v1_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *MonitorTemperatureResponse) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *MonitorTemperatureResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// --- Messages cho UploadMetrics ---
type UploadMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensorId string  `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Value    float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UploadMetricsRequest) Reset() {
	*x = UploadMetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensor_v1_sensor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetricsRequest) ProtoMessage() {}

func (x *UploadMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_v1_sensor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetricsRequest.ProtoReflect.Descriptor instead.
func (*UploadMetricsRequest) Descriptor() ([]byte, []int) {
	return file_sensor_v1_sensor_proto_rawDescGZIP(), []int{2}
}

func (x *UploadMetricsRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *UploadMetricsRequest) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UploadMetricsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalReceived int32  `protobuf:"varint,1,opt,name=total_received,json=totalReceived,proto3" json:"total_received,omitempty"`
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UploadMetricsResponse) Reset() {
	*x = UploadMetricsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensor_v1_sensor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetricsResponse) ProtoMessage() {}

func (x *UploadMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_v1_sensor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetricsResponse.ProtoReflect.Descriptor instead.
func (*UploadMetricsResponse) Descriptor() ([]byte, []int) {
	return file_sensor_v1_sensor_proto_rawDescGZIP(), []int{3}
}

func (x *UploadMetricsResponse) GetTotalReceived() int32 {
	if x != nil {
		return x.TotalReceived
	}
	return 0
}

func (x *UploadMetricsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// --- Messages cho LiveAlerts ---
type LiveAlertsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensorId string  `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Value    float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LiveAlertsRequest) Reset() {
	*x = LiveAlertsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensor_v1_sensor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveAlertsRequest) ProtoMessage() {}

func (x *LiveAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_v1_sensor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveAlertsRequest.ProtoReflect.Descriptor instead.
func (*LiveAlertsRequest) Descriptor() ([]byte, []int) {
	return file_sensor_v1_sensor_proto_rawDescGZIP(), []int{4}
}

func (x *LiveAlertsRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *LiveAlertsRequest) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type LiveAlertsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensorId string `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LiveAlertsResponse) Reset() {
	*x = LiveAlertsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensor_v1_sensor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveAlertsResponse) ProtoMessage() {}

func (x *LiveAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_v1_sensor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveAlertsResponse.ProtoReflect.Descriptor instead.
func (*LiveAlertsResponse) Descriptor() ([]byte, []int) {
	return file_sensor_v1_sensor_proto_rawDescGZIP(), []int{5}
}

func (x *LiveAlertsResponse) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *LiveAlertsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_sensor_v1_sensor_proto protoreflect.FileDescriptor

var file_sensor_v1_sensor_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x2e, 0x76, 0x31, 0x22, 0x38, 0x0a, 0x19, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x54, 0x65,
	0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x5c, 0x0a,
	0x1a, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74,
	0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x49, 0x0a, 0x14, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x56, 0x0a, 0x15, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x25, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x46,
	0x0a, 0x11, 0x4c, 0x69, 0x76, 0x65, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4b, 0x0a, 0x12, 0x4c, 0x69, 0x76, 0x65, 0x41, 0x6c,
	0x65, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0x99, 0x02, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x63, 0x0a, 0x12, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x24, 0x2e, 0x73, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x54,
	0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f,
	0x6e, 0x69, 0x74, 0x6f, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x54, 0x0a, 0x0d, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x1f, 0x2e, 0x73, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73,
	0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01,
	0x12, 0x4d, 0x0a, 0x0a, 0x4c, 0x69, 0x76, 0x65, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x12, 0x1c,
	0x2e, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x41,
	0x6c, 0x65, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73,
	0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x6f,
	0x75, 0x72, 0x2d, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x31,
	0x30, 0x31, 0x2f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sensor_v1_sensor_proto_rawDescOnce sync.Once
	file_sensor_v1_sensor_proto_rawDescData = file_sensor_v1_sensor_proto_rawDesc
)

func file_sensor_v1_sensor_proto_rawDescGZIP() []byte {
	file_sensor_v1_sensor_proto_rawDescOnce.Do(func() {
		file_sensor_v1_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(file_sensor_v1_sensor_proto_rawDescData)
	})
	return file_sensor_v1_sensor_proto_rawDescData
}

var file_sensor_v1_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sensor_v1_sensor_proto_goTypes = []interface{}{
	(*MonitorTemperatureRequest)(nil),  // 0: sensor.v1.MonitorTemperatureRequest
	(*MonitorTemperatureResponse)(nil), // 1: sensor.v1.MonitorTemperatureResponse
	(*UploadMetricsRequest)(nil),       // 2: sensor.v1.UploadMetricsRequest
	(*UploadMetricsResponse)(nil),      // 3: sensor.v1.UploadMetricsResponse
	(*LiveAlertsRequest)(nil),          // 4: sensor.v1.LiveAlertsRequest
	(*LiveAlertsResponse)(nil),         // 5: sensor.v1.LiveAlertsResponse
}
var file_sensor_v1_sensor_proto_depIdxs = []int32{
	0, // 0: sensor.v1.SensorService.MonitorTemperature:input_type -> sensor.v1.MonitorTemperatureRequest
	2, // 1: sensor.v1.SensorService.UploadMetrics:input_type -> sensor.v1.UploadMetricsRequest
	4, // 2: sensor.v1.SensorService.LiveAlerts:input_type -> sensor.v1.LiveAlertsRequest
	1, // 3: sensor.v1.SensorService.MonitorTemperature:output_type -> sensor.v1.MonitorTemperatureResponse
	3, // 4: sensor.v1.SensorService.UploadMetrics:output_type -> sensor.v1.UploadMetricsResponse
	5, // 5: sensor.v1.SensorService.LiveAlerts:output_type -> sensor.v1.LiveAlertsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sensor_v1_sensor_proto_init() }
func file_sensor_v1_sensor_proto_init() {
	if File_sensor_v1_sensor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sensor_v1_sensor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonitorTemperatureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sensor_v1_sensor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonitorTemperatureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sensor_v1_sensor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMetricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sensor_v1_sensor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMetricsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sensor_v1_sensor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveAlertsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sensor_v1_sensor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveAlertsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sensor_v1_sensor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sensor_v1_sensor_proto_goTypes,
		DependencyIndexes: file_sensor_v1_sensor_proto_depIdxs,
		MessageInfos:      file_sensor_v1_sensor_proto_msgTypes,
	}.Build()
	File_sensor_v1_sensor_proto = out.File
	file_sensor_v1_sensor_proto_rawDesc = nil
	file_sensor_v1_sensor_proto_goTypes = nil
	file_sensor_v1_sensor_proto_depIdxs = nil
}
