// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SensorServiceClient is the client API for SensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorServiceClient interface {
	// 1. Server Streaming
	MonitorTemperature(ctx context.Context, in *MonitorTemperatureRequest, opts ...grpc.CallOption) (SensorService_MonitorTemperatureClient, error)
	// 2. Client Streaming
	UploadMetrics(ctx context.Context, opts ...grpc.CallOption) (SensorService_UploadMetricsClient, error)
	// 3. Bi-directional Streaming
	LiveAlerts(ctx context.Context, opts ...grpc.CallOption) (SensorService_LiveAlertsClient, error)
}

type sensorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorServiceClient(cc grpc.ClientConnInterface) SensorServiceClient {
	return &sensorServiceClient{cc}
}

func (c *sensorServiceClient) MonitorTemperature(ctx context.Context, in *MonitorTemperatureRequest, opts ...grpc.CallOption) (SensorService_MonitorTemperatureClient, error) {
	stream, err := c.cc.NewStream(ctx, &SensorService_ServiceDesc.Streams[0], "/sensor.v1.SensorService/MonitorTemperature", opts...)
	if err != nil {
		return nil, err
	}
	x := &sensorServiceMonitorTemperatureClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SensorService_MonitorTemperatureClient interface {
	Recv() (*MonitorTemperatureResponse, error)
	grpc.ClientStream
}

type sensorServiceMonitorTemperatureClient struct {
	grpc.ClientStream
}

func (x *sensorServiceMonitorTemperatureClient) Recv() (*MonitorTemperatureResponse, error) {
	m := new(MonitorTemperatureResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sensorServiceClient) UploadMetrics(ctx context.Context, opts ...grpc.CallOption) (SensorService_UploadMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SensorService_ServiceDesc.Streams[1], "/sensor.v1.SensorService/UploadMetrics", opts...)
	if err != nil {
		return nil, err
	}
	x := &sensorServiceUploadMetricsClient{stream}
	return x, nil
}

type SensorService_UploadMetricsClient interface {
	Send(*UploadMetricsRequest) error
	CloseAndRecv() (*UploadMetricsResponse, error)
	grpc.ClientStream
}

type sensorServiceUploadMetricsClient struct {
	grpc.ClientStream
}

func (x *sensorServiceUploadMetricsClient) Send(m *UploadMetricsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sensorServiceUploadMetricsClient) CloseAndRecv() (*UploadMetricsResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadMetricsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sensorServiceClient) LiveAlerts(ctx context.Context, opts ...grpc.CallOption) (SensorService_LiveAlertsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SensorService_ServiceDesc.Streams[2], "/sensor.v1.SensorService/LiveAlerts", opts...)
	if err != nil {
		return nil, err
	}
	x := &sensorServiceLiveAlertsClient{stream}
	return x, nil
}

type SensorService_LiveAlertsClient interface {
	Send(*LiveAlertsRequest) error
	Recv() (*LiveAlertsResponse, error)
	grpc.ClientStream
}

type sensorServiceLiveAlertsClient struct {
	grpc.ClientStream
}

func (x *sensorServiceLiveAlertsClient) Send(m *LiveAlertsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sensorServiceLiveAlertsClient) Recv() (*LiveAlertsResponse, error) {
	m := new(LiveAlertsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SensorServiceServer is the server API for SensorService service.
// All implementations must embed UnimplementedSensorServiceServer
// for forward compatibility
type SensorServiceServer interface {
	// 1. Server Streaming
	MonitorTemperature(*MonitorTemperatureRequest, SensorService_MonitorTemperatureServer) error
	// 2. Client Streaming
	UploadMetrics(SensorService_UploadMetricsServer) error
	// 3. Bi-directional Streaming
	LiveAlerts(SensorService_LiveAlertsServer) error
	mustEmbedUnimplementedSensorServiceServer()
}

// UnimplementedSensorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSensorServiceServer struct {
}

func (UnimplementedSensorServiceServer) MonitorTemperature(*MonitorTemperatureRequest, SensorService_MonitorTemperatureServer) error {
	return status.Errorf(codes.Unimplemented, "method MonitorTemperature not implemented")
}
func (UnimplementedSensorServiceServer) UploadMetrics(SensorService_UploadMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadMetrics not implemented")
}
func (UnimplementedSensorServiceServer) LiveAlerts(SensorService_LiveAlertsServer) error {
	return status.Errorf(codes.Unimplemented, "method LiveAlerts not implemented")
}
func (UnimplementedSensorServiceServer) mustEmbedUnimplementedSensorServiceServer() {}

// UnsafeSensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorServiceServer will
// result in compilation errors.
type UnsafeSensorServiceServer interface {
	mustEmbedUnimplementedSensorServiceServer()
}

func RegisterSensorServiceServer(s grpc.ServiceRegistrar, srv SensorServiceServer) {
	s.RegisterService(&SensorService_ServiceDesc, srv)
}

func _SensorService_MonitorTemperature_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MonitorTemperatureRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SensorServiceServer).MonitorTemperature(m, &sensorServiceMonitorTemperatureServer{stream})
}

type SensorService_MonitorTemperatureServer interface {
	Send(*MonitorTemperatureResponse) error
	grpc.ServerStream
}

type sensorServiceMonitorTemperatureServer struct {
	grpc.ServerStream
}

func (x *sensorServiceMonitorTemperatureServer) Send(m *MonitorTemperatureResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SensorService_UploadMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SensorServiceServer).UploadMetrics(&sensorServiceUploadMetricsServer{stream})
}

type SensorService_UploadMetricsServer interface {
	SendAndClose(*UploadMetricsResponse) error
	Recv() (*UploadMetricsRequest, error)
	grpc.ServerStream
}

type sensorServiceUploadMetricsServer struct {
	grpc.ServerStream
}

func (x *sensorServiceUploadMetricsServer) SendAndClose(m *UploadMetricsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sensorServiceUploadMetricsServer) Recv() (*UploadMetricsRequest, error) {
	m := new(UploadMetricsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SensorService_LiveAlerts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SensorServiceServer).LiveAlerts(&sensorServiceLiveAlertsServer{stream})
}

type SensorService_LiveAlertsServer interface {
	Send(*LiveAlertsResponse) error
	Recv() (*LiveAlertsRequest, error)
	grpc.ServerStream
}

type sensorServiceLiveAlertsServer struct {
	grpc.ServerStream
}

func (x *sensorServiceLiveAlertsServer) Send(m *LiveAlertsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sensorServiceLiveAlertsServer) Recv() (*LiveAlertsRequest, error) {
	m := new(LiveAlertsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SensorService_ServiceDesc is the grpc.ServiceDesc for SensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sensor.v1.SensorService",
	HandlerType: (*SensorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MonitorTemperature",
			Handler:       _SensorService_MonitorTemperature_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadMetrics",
			Handler:       _SensorService_UploadMetrics_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "LiveAlerts",
			Handler:       _SensorService_LiveAlerts_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sensor/v1/sensor.proto",
}
