syntax = "proto3";

package user.v2;

import "buf/validate/validate.proto";

option go_package = "github.com/hungpdn/go-grpc-101/pd/user/v2";

service UserService {
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
}

message CreateUserRequest {
  // Name must be at least 3 characters long and at most 50 characters long
  string name = 1 [(buf.validate.field).string = {
    min_len: 3
    max_len: 50
  }];

  // Email must be a valid email address
  string email = 2 [(buf.validate.field).string.email = true];

  // Age must be between 18 and 100
  int32 age = 3 [(buf.validate.field).int32 = {
    gte: 18
    lte: 100
  }];
}

message CreateUserResponse {
  string message = 1;
}
