// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SecureServiceClient is the client API for SecureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecureServiceClient interface {
	GetSensitiveData(ctx context.Context, in *GetSensitiveDataRequest, opts ...grpc.CallOption) (*GetSensitiveDataResponse, error)
}

type secureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecureServiceClient(cc grpc.ClientConnInterface) SecureServiceClient {
	return &secureServiceClient{cc}
}

func (c *secureServiceClient) GetSensitiveData(ctx context.Context, in *GetSensitiveDataRequest, opts ...grpc.CallOption) (*GetSensitiveDataResponse, error) {
	out := new(GetSensitiveDataResponse)
	err := c.cc.Invoke(ctx, "/secure.v1.SecureService/GetSensitiveData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecureServiceServer is the server API for SecureService service.
// All implementations must embed UnimplementedSecureServiceServer
// for forward compatibility
type SecureServiceServer interface {
	GetSensitiveData(context.Context, *GetSensitiveDataRequest) (*GetSensitiveDataResponse, error)
	mustEmbedUnimplementedSecureServiceServer()
}

// UnimplementedSecureServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSecureServiceServer struct {
}

func (UnimplementedSecureServiceServer) GetSensitiveData(context.Context, *GetSensitiveDataRequest) (*GetSensitiveDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSensitiveData not implemented")
}
func (UnimplementedSecureServiceServer) mustEmbedUnimplementedSecureServiceServer() {}

// UnsafeSecureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecureServiceServer will
// result in compilation errors.
type UnsafeSecureServiceServer interface {
	mustEmbedUnimplementedSecureServiceServer()
}

func RegisterSecureServiceServer(s grpc.ServiceRegistrar, srv SecureServiceServer) {
	s.RegisterService(&SecureService_ServiceDesc, srv)
}

func _SecureService_GetSensitiveData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSensitiveDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureServiceServer).GetSensitiveData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secure.v1.SecureService/GetSensitiveData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureServiceServer).GetSensitiveData(ctx, req.(*GetSensitiveDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecureService_ServiceDesc is the grpc.ServiceDesc for SecureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secure.v1.SecureService",
	HandlerType: (*SecureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSensitiveData",
			Handler:    _SecureService_GetSensitiveData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secure/v1/secure.proto",
}
