package main

import (
	"context"
	"log/slog"
	"net"
	"net/http"
	"os"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	pb "github.com/hungpdn/go-grpc-101/pb/user/v1"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

// Standard gRPC Server Implementation
type userServer struct {
	pb.UnimplementedUserServiceServer
	logger *slog.Logger
}

func (s *userServer) GetUser(ctx context.Context, req *pb.GetUserRequest) (*pb.GetUserResponse, error) {
	s.logger.Info("business logic triggered", slog.String("user_id", req.GetUserId()))

	return &pb.GetUserResponse{
		UserId: req.GetUserId(),
		Name:   "Gateway User",
		Email:  "rest@production.local",
	}, nil
}

func main() {
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))
	ctx := context.Background()

	// 1. START NATIVE gRPC SERVER
	grpcListener, err := net.Listen("tcp", ":50058")
	if err != nil {
		logger.Error("failed to listen", slog.String("error", err.Error()))
		os.Exit(1)
	}

	grpcServer := grpc.NewServer()
	pb.RegisterUserServiceServer(grpcServer, &userServer{logger: logger})

	// Run gRPC server in a background goroutine
	go func() {
		logger.Info("native gRPC server running on :50058")
		if err := grpcServer.Serve(grpcListener); err != nil {
			logger.Error("grpc server failed", slog.String("error", err.Error()))
		}
	}()

	// 2. START HTTP REVERSE PROXY (gRPC-Gateway)
	// Create a client connection to the local gRPC server
	conn, err := grpc.NewClient("localhost:50058", grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		logger.Error("failed to dial server", slog.String("error", err.Error()))
		os.Exit(1)
	}

	gwmux := runtime.NewServeMux()

	// Register the handler. This function was automatically generated by the gateway plugin!
	err = pb.RegisterUserServiceHandler(ctx, gwmux, conn)
	if err != nil {
		logger.Error("failed to register gateway", slog.String("error", err.Error()))
		os.Exit(1)
	}

	// Start the HTTP server
	gwServer := &http.Server{
		Addr:    ":8080",
		Handler: gwmux,
	}

	logger.Info("REST/HTTP gateway running on :8080")
	if err := gwServer.ListenAndServe(); err != nil {
		logger.Error("gateway failed", slog.String("error", err.Error()))
	}
}
