# ==========================================
# GOLANG gRPC HIGH CONCURRENCY SYSCTL TUNE
# ==========================================

# 1. FILE DESCRIPTORS
# Allows the operating system to open a maximum of 1 million files (equivalent to 1 million TCP connections)
fs.file-max = 1000000

# 2. TCP BACKLOG (HÀNG ĐỢI)
# The maximum number of connections allowed to wait in the queue when the Go Server has not yet accepted()
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 65535

# 3. EPHEMERAL PORTS
# Expand the random port range so the Server can call other Microservices
net.ipv4.ip_local_port_range = 1024 65535

# 4. TIME_WAIT REUSE
# Allow immediate reuse of ports in TIME_WAIT state
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15

# 5. BUFFER SIZES
# Optimize buffer size (RAM) allocated for each TCP connection (increase data transfer speed)
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216